version: 1.3.4
cache: true
endpoints:
  custom:
    - name: "AnyGPT"
      apiKey: "${ANYGPT_API_KEY}"
      baseURL: "${ANYGPT_BASE_URL}"
      models:
        default:
          - "gpt-4o-mini"
        fetch: true
      titleConvo: true
      titleModel: "current_model"
      summarize: false
      summaryModel: "current_model"
